### ISSUE TITLE
non-functional requirements - bonus: snowcards

### ISSUE THREAD

**Issue by JesterAroundKettleObserveBreak** [20SEBastian03/PraktikumSoftwaretechnik2024_25#10]
- "011". Interoperability Requirements - Muss auf verschiedenen Geräten funktionieren + zusammenarbeiten
- "012". Efficiency Requirements -  So wenig wie möglich Arbeit, gehört mit zu performace. Muss nicht nur schnell sein sondern
auch effizient
- "013" Reliability Requirements Zuverlössigkeit: wie stabil? was kann zur Störung werden
- "014" Portability Requirements - soll auf verschiedenen Plattformen laufen zb. wenn OS gewechselt wird

**Comment by 20SEBastian03** [comment]
011 und 014 ist doch die Antwort das selbe? also muss auf verschiedenen Geräten laufen impliziert, es muss auf verschiedenen Betriebssystemen laufen

**Comment by JesterAroundKettleObserveBreak** [comment]
ich habe die Unterscheidung auch noch nicht ganz verstanden. Bin davon ausgegangen, dass Interoperabilty sich drauf bezieht, dass es zb. von Android die App in einer Sprache redet, die eine App auf Linux versteht, während es läuft (also das zb. Beide Versionen die selben Daten zugreifen können und evtl snychronisiert werden. 
Und bei Portablity, dass eine Version für jedes gewünschte OS zur Verfügung gestellt wird.

**Comment by 20SEBastian03** [comment]
Wäre das nicht zu umständlich im großen und ganzen, oder kann man das so flexibel programmieren? Mit sowas kenn ich mich nich aus

**Comment by JesterAroundKettleObserveBreak** [comment]
Aufwändig ist es sicher. Aber eine Anforderung bleibt es ja. ob wir das dann umsetzen (können) ist ja ne andere Frage

**Comment by 20SEBastian03** [comment]
hallo test
