### ISSUE TITLE
Vollständiges ausfüllen der Snowcards

### ISSUE THREAD

**Issue by JesterAroundKettleObserveBreak** [20SEBastian03/PraktikumSoftwaretechnik2024_25#18]
@20SEBastian03 kannst du da über die letzten nochmal drüber gucken (11-14) ob du was ergänzen magst?

**Comment by 20SEBastian03** [comment]
@JesterAroundKettleObserveBreak  Priority ist in high, medium, low einzuteilen, steht im Dok

**Comment by JesterAroundKettleObserveBreak** [comment]
ist jetzt gefixed :) danke!
